language: cpp

os: [linux, osx]
compiler: [gcc, clang]

addons:
  apt:
    packages: [cmake, gcc-multilib, g++-multilib]
    sources: [ubuntu-toolchain-r-test]

env:
  matrix:
    - BUILD_TYPE=Debug   CFLAGS=-m32 CXXFLAGS=-m32
    - BUILD_TYPE=Debug   CFLAGS=-m64 CXXFLAGS=-m64
    - BUILD_TYPE=Release CFLAGS=-m32 CXXFLAGS=-m32
    - BUILD_TYPE=Release CFLAGS=-m64 CXXFLAGS=-m64

matrix:
  exclude:
    - os: osx
      compiler: gcc

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_PACKAGE="https://cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz"
      mkdir -p deps/cmake
      wget --no-check-certificate --quiet -O - ${CMAKE_PACKAGE} | tar --strip-components=1 -xz -C deps/cmake
      export PATH=${TRAVIS_BUILD_DIR}/deps/cmake/bin:${PATH}
    else
      brew update
      brew outdated cmake || brew upgrade cmake
    fi
  - |
    mkdir -p deps/asmjit
    git clone --depth=1 https://github.com/asmjit/asmjit.git deps/asmjit

before_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DASMJIT_DIR="../deps/asmjit" -DASMTK_BUILD_TEST=1
  - cd ..

script:
  - cd build
  - make
  - cd ..
  - ./build/asmtk_test_x86
